name: "linter"

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  linter:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@latest
      - uses: actions/setup-node@latest
        with:
          node-version: 20
      - name: "Packages"
        run: npm install
      - name: "Prettier"
        run: npm run prettier:check
      - name: "Audit"
        run: npm audit
